-- Add document evidence fields

ALTER TABLE "EmployeeDocument"
ADD COLUMN IF NOT EXISTS "blobPath" TEXT,
ADD COLUMN IF NOT EXISTS "documentReference" TEXT,
ADD COLUMN IF NOT EXISTS "fileHash" TEXT,
ADD COLUMN IF NOT EXISTS "fileMimeType" TEXT,
ADD COLUMN IF NOT EXISTS "fileSize" INTEGER,
ADD COLUMN IF NOT EXISTS "uploadedIp" TEXT,
ADD COLUMN IF NOT EXISTS "uploadedUserAgent" TEXT;

ALTER TABLE "OwnerDocument"
ADD COLUMN IF NOT EXISTS "blobPath" TEXT,
ADD COLUMN IF NOT EXISTS "documentReference" TEXT,
ADD COLUMN IF NOT EXISTS "fileHash" TEXT,
ADD COLUMN IF NOT EXISTS "fileMimeType" TEXT,
ADD COLUMN IF NOT EXISTS "fileSize" INTEGER,
ADD COLUMN IF NOT EXISTS "uploadedIp" TEXT,
ADD COLUMN IF NOT EXISTS "uploadedUserAgent" TEXT;
